## CREATE A TIKINTER INTERFACE THAT HAS 2 BUTTONS, ONE THAT OPENS THE STANDARD TABS
## AND ANOTHER THAT SWITCHES TKINTER FRAME TO ANOTHER FRAME WITHIN THE FILE post_description_file_generator.py
import os
import shutil
import time
from tkinter import *
import tkinter as tk
from tkinter import ttk
from ttkthemes import ThemedTk
import webbrowser
from tkinter import messagebox
from tkinter import filedialog
## PANDAS FOR PARSING TABLE STYLE ELEMENTS
import pandas as pd
## CONNECTION TO LOCAL SQL SERVER DATABASE
from sql_connect import connect_to_sql
from generate_sql_db_if_not_exists import create_database, create_tables
from sql_utils import *
import json
## DOWNLOADING INSTAGRAM POSTS
import instaloader
from instaloader import *

## GENERAL SETTINGS
STANDARD_SIZE=(600, 400)
ALT_SIZE=(600, 300)
STANDARD_X_PADDING = 10
STANDARD_Y_PADDING = 10
STANDARD_Y_POSITION = 75 ## THIS LINES UP ALL THE MAIN 4 BUTTONS VERTICALLY
MAIN_BG_COLOR = '#F0F8FF'
STANDARD_LABEL_HEIGHT_REDUCER = 0.5
DOWNLOAD_CONFIG_FILE_NAME = "download_config.json"
DOWNLOAD_REPOSITORY_CONFIG = os.getcwd() + f"\\config\\"
DOWNLOAD_REPOSITORY = os.getcwd() + "\\MediaDownload"    

## BUTTONS SETTINGS
STANDARD_BUTTON_DIMENSIONS = (150, 40)
STANDARD_LABEL_DIMENSIONS = (250, 50)

##############################################################################################################################################
## MAIN WINDOW SETTINGS
## LABEL
MAIN_WINDOW_LABEL_DIMENSIONS = (STANDARD_LABEL_DIMENSIONS[0], STANDARD_LABEL_DIMENSIONS[1])
MAIN_WINDOW_LABEL_X_POSITION = (STANDARD_SIZE[0]/2)-(MAIN_WINDOW_LABEL_DIMENSIONS[0]/2)
MAIN_WINDOW_LABEL_Y_POSITION = STANDARD_Y_PADDING

## FUNCTIONS
OPEN_TABS_BUTTON_DIMENSIONS = (STANDARD_BUTTON_DIMENSIONS[0], STANDARD_BUTTON_DIMENSIONS[1])
EDIT_URLS_BUTTON_DIMENSIONS = (STANDARD_BUTTON_DIMENSIONS[0], STANDARD_BUTTON_DIMENSIONS[1])

OPEN_TABS_X_POSITION = (STANDARD_SIZE[0]/2)-((STANDARD_BUTTON_DIMENSIONS[0]*2 + 10)/2) ## THIS LINE CENTERS ALL THE BUTTONS HORIZONTALLY
OPEN_TABS_Y_POSITION = STANDARD_Y_POSITION
EDIT_URLS_X_POSITION = OPEN_TABS_X_POSITION
EDIT_URLS_Y_POSITION = OPEN_TABS_Y_POSITION + OPEN_TABS_BUTTON_DIMENSIONS[1] + STANDARD_Y_PADDING


OPEN_FOLDERS_BUTTON_DIMENSIONS = (STANDARD_BUTTON_DIMENSIONS[0], STANDARD_BUTTON_DIMENSIONS[1])
EDIT_LOCAL_PATHS_BUTTON_DIMENSIONS = (STANDARD_BUTTON_DIMENSIONS[0], STANDARD_BUTTON_DIMENSIONS[1])

OPEN_FOLDERS_BUTTON_X_POSITION = OPEN_TABS_X_POSITION + OPEN_TABS_BUTTON_DIMENSIONS[0] + STANDARD_X_PADDING
OPEN_FOLDERS_BUTTON_Y_POSITION = STANDARD_Y_POSITION
EDIT_LOCAL_PATHS_BUTTON_X_POSITION = OPEN_FOLDERS_BUTTON_X_POSITION
EDIT_LOCAL_PATHS_BUTTON_Y_POSITION = OPEN_FOLDERS_BUTTON_Y_POSITION + OPEN_FOLDERS_BUTTON_DIMENSIONS[1] + STANDARD_Y_PADDING

POST_DESCRIPTION_FILE_GENERATOR_BUTTON_DIMENSIONS = (STANDARD_BUTTON_DIMENSIONS[0]*2, STANDARD_BUTTON_DIMENSIONS[1])
POST_DESCRIPTION_FILE_GENERATOR_BUTTON_X_POSITION = (STANDARD_SIZE[0]/2)-(POST_DESCRIPTION_FILE_GENERATOR_BUTTON_DIMENSIONS[0]/2)
POST_DESCRIPTION_FILE_GENERATOR_BUTTON_Y_POSITION = EDIT_URLS_Y_POSITION + EDIT_URLS_BUTTON_DIMENSIONS[1] + STANDARD_Y_PADDING

DOWNLOAD_INSTAGRAM_POSTS_EDIT_BUTTON_DIMENSIONS = (STANDARD_BUTTON_DIMENSIONS[0]*2, STANDARD_BUTTON_DIMENSIONS[1])
DOWNLOAD_INSTAGRAM_POSTS_EDIT_BUTTON_X_POSITION = (STANDARD_SIZE[0]/2)-(DOWNLOAD_INSTAGRAM_POSTS_EDIT_BUTTON_DIMENSIONS[0]/2)
DOWNLOAD_INSTAGRAM_POSTS_EDIT_BUTTON_Y_POSITION = POST_DESCRIPTION_FILE_GENERATOR_BUTTON_Y_POSITION + POST_DESCRIPTION_FILE_GENERATOR_BUTTON_DIMENSIONS[1] + STANDARD_Y_PADDING
##############################################################################################################################################
## EDIT URLS WINDOW SETTINGS
## LABEL
EDIT_URLS_WINDOW_LABEL_DIMENSIONS = (STANDARD_LABEL_DIMENSIONS[0], STANDARD_LABEL_DIMENSIONS[1])
EDIT_URLS_WINDOW_LABEL_X_POSITION = (STANDARD_SIZE[0]/2)-(EDIT_URLS_WINDOW_LABEL_DIMENSIONS[0]/2)
EDIT_URLS_WINDOW_LABEL_Y_POSITION = STANDARD_Y_PADDING

## FUNCTIONS
INSERT_NEW_URL_BUTTON_DIMENSIONS = (STANDARD_BUTTON_DIMENSIONS[0], STANDARD_BUTTON_DIMENSIONS[1])
DELETE_URL_EDIT_BUTTON_DIMENSIONS = (STANDARD_BUTTON_DIMENSIONS[0], STANDARD_BUTTON_DIMENSIONS[1])

INSERT_NEW_URL_EDIT_BUTTON_X_POSITION = (STANDARD_SIZE[0]/2)-((STANDARD_BUTTON_DIMENSIONS[0]*2 + 10)/2) ## THIS LINE CENTERS ALL THE BUTTONS HORIZONTALLY
INSERT_NEW_URL_EDIT_BUTTON_Y_POSITION = STANDARD_Y_POSITION
DELETE_URL_EDIT_BUTTON_X_POSITION = INSERT_NEW_URL_EDIT_BUTTON_X_POSITION + INSERT_NEW_URL_BUTTON_DIMENSIONS[0] + STANDARD_X_PADDING
DELETE_URL_EDIT_BUTTON_Y_POSITION = INSERT_NEW_URL_EDIT_BUTTON_Y_POSITION

## BACK BUTTON
EDIT_URLS_BACK_BUTTON_DIMENSIONS = (STANDARD_BUTTON_DIMENSIONS[0], STANDARD_BUTTON_DIMENSIONS[1])
EDIT_URLS_BACK_BUTTON_X_POSITION = (STANDARD_SIZE[0]/2)-(EDIT_URLS_BACK_BUTTON_DIMENSIONS[0]/2)
EDIT_URLS_BACK_BUTTON_Y_POSITION = DELETE_URL_EDIT_BUTTON_Y_POSITION + DELETE_URL_EDIT_BUTTON_DIMENSIONS[1] + STANDARD_Y_PADDING
##############################################################################################################################################
## EDIT LOCAL PATHS WINDOW SETTINGS
## LABEL
EDIT_LOCAL_PATHS_WINDOW_LABEL_DIMENSIONS = (STANDARD_LABEL_DIMENSIONS[0], STANDARD_LABEL_DIMENSIONS[1])
EDIT_LOCAL_PATHS_WINDOW_LABEL_X_POSITION = (STANDARD_SIZE[0]/2)-(EDIT_LOCAL_PATHS_WINDOW_LABEL_DIMENSIONS[0]/2)
EDIT_LOCAL_PATHS_WINDOW_LABEL_Y_POSITION = STANDARD_Y_PADDING

## FUNCTIONS
DELETE_LOCAL_PATH_EDIT_BUTTON_DIMENSIONS = (STANDARD_BUTTON_DIMENSIONS[0], STANDARD_BUTTON_DIMENSIONS[1])
INSERT_NEW_LOCAL_PATH_EDIT_BUTTON_DIMENSIONS = (STANDARD_BUTTON_DIMENSIONS[0], STANDARD_BUTTON_DIMENSIONS[1])

INSERT_NEW_LOCAL_PATH_EDIT_BUTTON_X_POSITION = (STANDARD_SIZE[0]/2)-((INSERT_NEW_LOCAL_PATH_EDIT_BUTTON_DIMENSIONS[0]*2 + 10)/2) ## THIS LINE CENTERS ALL THE BUTTONS HORIZONTALLY
INSERT_NEW_LOCAL_PATH_EDIT_BUTTON_Y_POSITION = STANDARD_Y_POSITION
DELETE_LOCAL_PATH_EDIT_BUTTON_X_POSITION = INSERT_NEW_LOCAL_PATH_EDIT_BUTTON_X_POSITION + INSERT_NEW_LOCAL_PATH_EDIT_BUTTON_DIMENSIONS[0] + STANDARD_X_PADDING
DELETE_LOCAL_PATH_EDIT_BUTTON_Y_POSITION = INSERT_NEW_LOCAL_PATH_EDIT_BUTTON_Y_POSITION


## BACK BUTTON
EDIT_LOCAL_PATHS_BACK_BUTTON_DIMENSIONS = (STANDARD_BUTTON_DIMENSIONS[0], STANDARD_BUTTON_DIMENSIONS[1])
EDIT_LOCAL_PATHS_BACK_BUTTON_X_POSITION = (STANDARD_SIZE[0]/2)-(EDIT_LOCAL_PATHS_BACK_BUTTON_DIMENSIONS[0]/2)
EDIT_LOCAL_PATHS_BACK_BUTTON_Y_POSITION = INSERT_NEW_LOCAL_PATH_EDIT_BUTTON_Y_POSITION + INSERT_NEW_LOCAL_PATH_EDIT_BUTTON_DIMENSIONS[1] + STANDARD_Y_PADDING
##############################################################################################################################################
## INSERT NEW URL WINDOW SETTINGS
## LABEL
INSERT_NEW_URL_WINDOW_LABEL_DIMENSIONS = (STANDARD_LABEL_DIMENSIONS[0], STANDARD_LABEL_DIMENSIONS[1])
INSERT_NEW_URL_WINDOW_LABEL_X_POSITION = (STANDARD_SIZE[0]/2)-(INSERT_NEW_URL_WINDOW_LABEL_DIMENSIONS[0]/2)
INSERT_NEW_URL_WINDOW_LABEL_Y_POSITION = STANDARD_Y_PADDING

## FUNCTIONS
URL_ENTRY_DIMENSIONS = (STANDARD_BUTTON_DIMENSIONS[0], STANDARD_BUTTON_DIMENSIONS[1])
INSERT_URL_BUTTON_DIMENSIONS = (STANDARD_BUTTON_DIMENSIONS[0], STANDARD_BUTTON_DIMENSIONS[1])

URL_ENTRY_X_POSITION = (STANDARD_SIZE[0]/2)-(URL_ENTRY_DIMENSIONS[0]/2) ## THIS LINE CENTERS ALL THE BUTTONS HORIZONTALLY
URL_ENTRY_Y_POSITION = STANDARD_Y_POSITION
INSERT_URL_BUTTON_X_POSITION = URL_ENTRY_X_POSITION
INSERT_URL_BUTTON_Y_POSITION = URL_ENTRY_Y_POSITION + URL_ENTRY_DIMENSIONS[1] + STANDARD_Y_PADDING

## BACK BUTTON
INSERT_NEW_URL_BACK_BUTTON_DIMENSIONS = (STANDARD_BUTTON_DIMENSIONS[0], STANDARD_BUTTON_DIMENSIONS[1])
INSERT_NEW_URL_BACK_BUTTON_X_POSITION = (STANDARD_SIZE[0]/2)-(INSERT_NEW_URL_BACK_BUTTON_DIMENSIONS[0]/2)
INSERT_NEW_URL_BACK_BUTTON_Y_POSITION = INSERT_URL_BUTTON_Y_POSITION + INSERT_URL_BUTTON_DIMENSIONS[1] + STANDARD_Y_PADDING
##############################################################################################################################################
## INSERT NEW LOCAL PATH WINDOW SETTINGS
## LABEL
INSERT_NEW_LOCAL_PATH_WINDOW_LABEL_DIMENSIONS = (STANDARD_LABEL_DIMENSIONS[0], STANDARD_LABEL_DIMENSIONS[1])
INSERT_NEW_LOCAL_PATH_WINDOW_LABEL_X_POSITION = (STANDARD_SIZE[0]/2)-(INSERT_NEW_LOCAL_PATH_WINDOW_LABEL_DIMENSIONS[0]/2)
INSERT_NEW_LOCAL_PATH_WINDOW_LABEL_Y_POSITION = STANDARD_Y_PADDING

## FUNCTIONS
LOCAL_PATH_ENTRY_DIMENSIONS = (STANDARD_BUTTON_DIMENSIONS[0], STANDARD_BUTTON_DIMENSIONS[1])
INSERT_LOCAL_PATH_BUTTON_DIMENSIONS = (STANDARD_BUTTON_DIMENSIONS[0], STANDARD_BUTTON_DIMENSIONS[1])

LOCAL_PATH_ENTRY_X_POSITION = (STANDARD_SIZE[0]/2)-(LOCAL_PATH_ENTRY_DIMENSIONS[0]/2) ## THIS LINE CENTERS ALL THE BUTTONS HORIZONTALLY
LOCAL_PATH_ENTRY_Y_POSITION = STANDARD_Y_POSITION
INSERT_LOCAL_PATH_BUTTON_X_POSITION = LOCAL_PATH_ENTRY_X_POSITION
INSERT_LOCAL_PATH_BUTTON_Y_POSITION = LOCAL_PATH_ENTRY_Y_POSITION + LOCAL_PATH_ENTRY_DIMENSIONS[1] + STANDARD_Y_PADDING

## BROWSE BUTTON
BROWSE_BUTTON_DIMENSIONS = (STANDARD_BUTTON_DIMENSIONS[0], STANDARD_BUTTON_DIMENSIONS[1])
BROWSE_BUTTON_X_POSITION = (STANDARD_SIZE[0]/2)-(BROWSE_BUTTON_DIMENSIONS[0]/2)
BROWSE_BUTTON_Y_POSITION = INSERT_LOCAL_PATH_BUTTON_Y_POSITION + INSERT_LOCAL_PATH_BUTTON_DIMENSIONS[1] + STANDARD_Y_PADDING

## BACK BUTTON
INSERT_NEW_LOCAL_PATH_BACK_BUTTON_DIMENSIONS = (STANDARD_BUTTON_DIMENSIONS[0], STANDARD_BUTTON_DIMENSIONS[1])
INSERT_NEW_LOCAL_PATH_BACK_BUTTON_X_POSITION = (STANDARD_SIZE[0]/2)-(INSERT_NEW_LOCAL_PATH_BACK_BUTTON_DIMENSIONS[0]/2)
INSERT_NEW_LOCAL_PATH_BACK_BUTTON_Y_POSITION = BROWSE_BUTTON_Y_POSITION + BROWSE_BUTTON_DIMENSIONS[1] + STANDARD_Y_PADDING
##############################################################################################################################################
## DELETE URLS WINDOW SETTINGS
## LABEL
DELETE_URLS_WINDOW_LABEL_DIMENSIONS = (STANDARD_LABEL_DIMENSIONS[0], STANDARD_LABEL_DIMENSIONS[1])
DELETE_URLS_WINDOW_LABEL_X_POSITION = (STANDARD_SIZE[0]/2)-(DELETE_URLS_WINDOW_LABEL_DIMENSIONS[0]/2)
DELETE_URLS_WINDOW_LABEL_Y_POSITION = STANDARD_Y_PADDING

## FUNCTIONS
DELETE_URLS_OPTION_MENU_DIMENSIONS = (STANDARD_BUTTON_DIMENSIONS[0], STANDARD_BUTTON_DIMENSIONS[1])
DELETE_URLS_BUTTON_DIMENSIONS = (STANDARD_BUTTON_DIMENSIONS[0], STANDARD_BUTTON_DIMENSIONS[1])

DELETE_URL_OPTION_MENU_X_POSITION = (STANDARD_SIZE[0]/2)-(DELETE_URLS_OPTION_MENU_DIMENSIONS[0]/2) ## THIS LINE CENTERS ALL THE BUTTONS HORIZONTALLY
DELETE_URL_OPTION_MENU_Y_POSITION = STANDARD_Y_POSITION
DELETE_URL_BUTTON_X_POSITION = DELETE_URL_OPTION_MENU_X_POSITION
DELETE_URL_BUTTON_Y_POSITION = DELETE_URL_OPTION_MENU_Y_POSITION + DELETE_URLS_OPTION_MENU_DIMENSIONS[1] + STANDARD_Y_PADDING

## BACK BUTTON
DELETE_URLS_BACK_BUTTON_DIMENSIONS = (STANDARD_BUTTON_DIMENSIONS[0], STANDARD_BUTTON_DIMENSIONS[1])
DELETE_URLS_BACK_BUTTON_X_POSITION = (STANDARD_SIZE[0]/2)-(DELETE_URLS_BACK_BUTTON_DIMENSIONS[0]/2)
DELETE_URLS_BACK_BUTTON_Y_POSITION = DELETE_URL_OPTION_MENU_Y_POSITION + DELETE_URLS_BUTTON_DIMENSIONS[1] + STANDARD_Y_PADDING
##############################################################################################################################################
## DELETE LOCAL PATHS WINDOW SETTINGS
## LABEL
DELETE_LOCAL_PATHS_WINDOW_LABEL_DIMENSIONS = (STANDARD_LABEL_DIMENSIONS[0], STANDARD_LABEL_DIMENSIONS[1])
DELETE_LOCAL_PATHS_WINDOW_LABEL_X_POSITION = (STANDARD_SIZE[0]/2)-(DELETE_LOCAL_PATHS_WINDOW_LABEL_DIMENSIONS[0]/2)
DELETE_LOCAL_PATHS_WINDOW_LABEL_Y_POSITION = STANDARD_Y_PADDING

## FUNCTIONS
DELETE_LOCAL_PATHS_OPTION_MENU_DIMENSIONS = (STANDARD_BUTTON_DIMENSIONS[0], STANDARD_BUTTON_DIMENSIONS[1])
DELETE_LOCAL_PATHS_BUTTON_DIMENSIONS = (STANDARD_BUTTON_DIMENSIONS[0], STANDARD_BUTTON_DIMENSIONS[1])

DELETE_LOCAL_PATHS_OPTION_MENU_X_POSITION = (STANDARD_SIZE[0]/2)-(DELETE_LOCAL_PATHS_OPTION_MENU_DIMENSIONS[0]/2) ## THIS LINE CENTERS ALL THE BUTTONS HORIZONTALLY
DELETE_LOCAL_PATHS_OPTION_MENU_Y_POSITION = STANDARD_Y_POSITION
DELETE_LOCAL_PATHS_BUTTON_X_POSITION = DELETE_LOCAL_PATHS_OPTION_MENU_X_POSITION
DELETE_LOCAL_PATHS_BUTTON_Y_POSITION = DELETE_LOCAL_PATHS_OPTION_MENU_Y_POSITION + DELETE_LOCAL_PATHS_OPTION_MENU_DIMENSIONS[1] + STANDARD_Y_PADDING
##############################################################################################################################################
## POST DESCRIPTION FILE GENERATOR WINDOW SETTINGS
## LABELS
POST_DESCRIPTION_FILE_GENERATOR_WINDOW_LABEL_DIMENSIONS = (STANDARD_LABEL_DIMENSIONS[0]*1.3, STANDARD_LABEL_DIMENSIONS[1])
POST_DESCRIPTION_FILE_GENERATOR_WINDOW_LABEL_X_POSITION = (STANDARD_SIZE[0]/2)-(POST_DESCRIPTION_FILE_GENERATOR_WINDOW_LABEL_DIMENSIONS[0]/2)
POST_DESCRIPTION_FILE_GENERATOR_WINDOW_LABEL_Y_POSITION = STANDARD_Y_PADDING


## NUMBER OF POSTS LABEL
POST_DESCRIPTION_NUMBER_OF_POSTS_LABEL_DIMENSIONS = (STANDARD_LABEL_DIMENSIONS[0], STANDARD_LABEL_DIMENSIONS[1]*STANDARD_LABEL_HEIGHT_REDUCER)
POST_DESCRIPTION_NUMBER_OF_POSTS_LABEL_X_POSITION = (STANDARD_SIZE[0]/2)-(POST_DESCRIPTION_NUMBER_OF_POSTS_LABEL_DIMENSIONS[0]/2)
POST_DESCRIPTION_NUMBER_OF_POSTS_LABEL_Y_POSITION = POST_DESCRIPTION_FILE_GENERATOR_WINDOW_LABEL_Y_POSITION + POST_DESCRIPTION_FILE_GENERATOR_WINDOW_LABEL_DIMENSIONS[1] + STANDARD_Y_PADDING

## NUMBER OF POSTS ENTRY
NUMBER_OF_POSTS_ENTRY_DIMENSIONS = (STANDARD_BUTTON_DIMENSIONS[0], STANDARD_BUTTON_DIMENSIONS[1])
NUMBER_OF_POSTS_ENTRY_X_POSITION = (STANDARD_SIZE[0]/2)-(NUMBER_OF_POSTS_ENTRY_DIMENSIONS[0]/2)
NUMBER_OF_POSTS_ENTRY_Y_POSITION = POST_DESCRIPTION_NUMBER_OF_POSTS_LABEL_Y_POSITION + POST_DESCRIPTION_NUMBER_OF_POSTS_LABEL_DIMENSIONS[1] + STANDARD_Y_PADDING

## INITIAL POST NUMBER LABEL
POST_DESCRIPTION_INITIAL_POST_NUMBER_LABEL_DIMENSIONS = (STANDARD_LABEL_DIMENSIONS[0], STANDARD_LABEL_DIMENSIONS[1]*STANDARD_LABEL_HEIGHT_REDUCER)
POST_DESCRIPTION_INITIAL_POST_NUMBER_LABEL_X_POSITION = (STANDARD_SIZE[0]/2)-(POST_DESCRIPTION_INITIAL_POST_NUMBER_LABEL_DIMENSIONS[0]/2)
POST_DESCRIPTION_INITIAL_POST_NUMBER_LABEL_Y_POSITION = NUMBER_OF_POSTS_ENTRY_Y_POSITION + NUMBER_OF_POSTS_ENTRY_DIMENSIONS[1] + STANDARD_Y_PADDING

## INITIAL POST NUMBER ENTRY
INITIAL_POST_NUMBER_ENTRY_DIMENSIONS = (STANDARD_BUTTON_DIMENSIONS[0], STANDARD_BUTTON_DIMENSIONS[1])
INITIAL_POST_NUMBER_ENTRY_X_POSITION = (STANDARD_SIZE[0]/2)-(INITIAL_POST_NUMBER_ENTRY_DIMENSIONS[0]/2)
INITIAL_POST_NUMBER_ENTRY_Y_POSITION = POST_DESCRIPTION_INITIAL_POST_NUMBER_LABEL_Y_POSITION + POST_DESCRIPTION_INITIAL_POST_NUMBER_LABEL_DIMENSIONS[1] + STANDARD_Y_PADDING

## CREATE FILES BUTTON
CREATE_FILES_BUTTON_DIMENSIONS = (STANDARD_BUTTON_DIMENSIONS[0], STANDARD_BUTTON_DIMENSIONS[1])
CREATE_FILES_BUTTON_X_POSITION = (STANDARD_SIZE[0]/2)-(CREATE_FILES_BUTTON_DIMENSIONS[0]/2)
CREATE_FILES_BUTTON_Y_POSITION = INITIAL_POST_NUMBER_ENTRY_Y_POSITION + INITIAL_POST_NUMBER_ENTRY_DIMENSIONS[1] + STANDARD_Y_PADDING
##############################################################################################################################################
## DOWNLOAD INSTAGRAM POSTS WINDOW SETTINGS
## LABELS
DOWNLOAD_INSTAGRAM_POSTS_WINDOW_LABEL_DIMENSIONS = (STANDARD_LABEL_DIMENSIONS[0]*1.3, STANDARD_LABEL_DIMENSIONS[1])
DOWNLOAD_INSTAGRAM_POSTS_WINDOW_LABEL_X_POSITION = (STANDARD_SIZE[0]/2)-(DOWNLOAD_INSTAGRAM_POSTS_WINDOW_LABEL_DIMENSIONS[0]/2)
DOWNLOAD_INSTAGRAM_POSTS_WINDOW_LABEL_Y_POSITION = STANDARD_Y_PADDING

## LINK LABEL
DOWNLOAD_INSTAGRAM_POSTS_LINK_LABEL_DIMENSIONS = (STANDARD_LABEL_DIMENSIONS[0], STANDARD_LABEL_DIMENSIONS[1]*STANDARD_LABEL_HEIGHT_REDUCER)
DOWNLOAD_INSTAGRAM_POSTS_LINK_LABEL_X_POSITION = (STANDARD_SIZE[0]/2)-(DOWNLOAD_INSTAGRAM_POSTS_LINK_LABEL_DIMENSIONS[0]/2)
DOWNLOAD_INSTAGRAM_POSTS_LINK_LABEL_Y_POSITION = DOWNLOAD_INSTAGRAM_POSTS_WINDOW_LABEL_Y_POSITION + DOWNLOAD_INSTAGRAM_POSTS_WINDOW_LABEL_DIMENSIONS[1] + STANDARD_Y_PADDING

## LINK ENTRY AND DOWNLOAD BUTTON
DOWNLOAD_INSTAGRAM_POSTS_LINK_ENTRY_DIMENSIONS = (STANDARD_BUTTON_DIMENSIONS[0], STANDARD_BUTTON_DIMENSIONS[1])
DOWNLOAD_INSTAGRAM_POSTS_DOWNLOAD_BUTTON_DIMENSIONS = (STANDARD_BUTTON_DIMENSIONS[0], STANDARD_BUTTON_DIMENSIONS[1])

DOWNLOAD_INSTAGRAM_POSTS_LINK_ENTRY_X_POSITION = (STANDARD_SIZE[0]/2)-((DOWNLOAD_INSTAGRAM_POSTS_LINK_ENTRY_DIMENSIONS[0]+DOWNLOAD_INSTAGRAM_POSTS_DOWNLOAD_BUTTON_DIMENSIONS[0]+STANDARD_X_PADDING)/2)
DOWNLOAD_INSTAGRAM_POSTS_LINK_ENTRY_Y_POSITION = DOWNLOAD_INSTAGRAM_POSTS_LINK_LABEL_Y_POSITION + DOWNLOAD_INSTAGRAM_POSTS_LINK_LABEL_DIMENSIONS[1] + STANDARD_Y_PADDING
DOWNLOAD_INSTAGRAM_POSTS_DOWNLOAD_BUTTON_X_POSITION = DOWNLOAD_INSTAGRAM_POSTS_LINK_ENTRY_X_POSITION + DOWNLOAD_INSTAGRAM_POSTS_LINK_ENTRY_DIMENSIONS[0] + STANDARD_X_PADDING
DOWNLOAD_INSTAGRAM_POSTS_DOWNLOAD_BUTTON_Y_POSITION = DOWNLOAD_INSTAGRAM_POSTS_LINK_ENTRY_Y_POSITION

## FILE NAME ENTRY AND LABEL
DOWNLOAD_INSTAGRAM_POSTS_FILE_NAME_ENTRY_DIMENSIONS = (STANDARD_BUTTON_DIMENSIONS[0], STANDARD_BUTTON_DIMENSIONS[1])
DOWNLOAD_INSTAGRAM_POSTS_FILE_NAME_LABEL_DIMENSIONS = (STANDARD_LABEL_DIMENSIONS[0], STANDARD_LABEL_DIMENSIONS[1]*STANDARD_LABEL_HEIGHT_REDUCER)

DOWNLOAD_INSTAGRAM_POSTS_FILE_NAME_LABEL_X_POSITION = (STANDARD_SIZE[0]/2)-(DOWNLOAD_INSTAGRAM_POSTS_FILE_NAME_LABEL_DIMENSIONS[0]/2)
DOWNLOAD_INSTAGRAM_POSTS_FILE_NAME_LABEL_Y_POSITION = DOWNLOAD_INSTAGRAM_POSTS_DOWNLOAD_BUTTON_Y_POSITION + DOWNLOAD_INSTAGRAM_POSTS_DOWNLOAD_BUTTON_DIMENSIONS[1] + STANDARD_Y_PADDING
DOWNLOAD_INSTAGRAM_POSTS_FILE_NAME_ENTRY_X_POSITION = (STANDARD_SIZE[0]/2)-(DOWNLOAD_INSTAGRAM_POSTS_FILE_NAME_ENTRY_DIMENSIONS[0]/2)
DOWNLOAD_INSTAGRAM_POSTS_FILE_NAME_ENTRY_Y_POSITION = DOWNLOAD_INSTAGRAM_POSTS_FILE_NAME_LABEL_Y_POSITION + DOWNLOAD_INSTAGRAM_POSTS_FILE_NAME_LABEL_DIMENSIONS[1] + STANDARD_Y_PADDING

## LABEL SHOW CURRENT DOWNLOAD REPOSITORY
DOWNLOAD_INSTAGRAM_POSTS_DOWNLOAD_PATH_LABEL_DIMENSIONS = (STANDARD_LABEL_DIMENSIONS[0], STANDARD_LABEL_DIMENSIONS[1]*STANDARD_LABEL_HEIGHT_REDUCER)
DOWNLOAD_INSTAGRAM_POSTS_DOWNLOAD_PATH_LABEL_X_POSITION = (STANDARD_SIZE[0]/2)-(DOWNLOAD_INSTAGRAM_POSTS_DOWNLOAD_PATH_LABEL_DIMENSIONS[0]/2)
DOWNLOAD_INSTAGRAM_POSTS_DOWNLOAD_PATH_LABEL_Y_POSITION = DOWNLOAD_INSTAGRAM_POSTS_FILE_NAME_ENTRY_Y_POSITION + DOWNLOAD_INSTAGRAM_POSTS_FILE_NAME_ENTRY_DIMENSIONS[1] + STANDARD_Y_PADDING

## CHANGE DOWNLOAD ENTRY AND BROWSE BUTTON
DOWNLOAD_INSTAGRAM_POSTS_CHANGE_DOWNLOAD_PATH_BUTTON_DIMENSIONS = (STANDARD_BUTTON_DIMENSIONS[0], STANDARD_BUTTON_DIMENSIONS[1])
DOWNLOAD_INSTAGRAM_POSTS_DOWNLOAD_PATH_ENTRY_DIMENSIONS = (STANDARD_BUTTON_DIMENSIONS[0], STANDARD_BUTTON_DIMENSIONS[1])

DOWNLOAD_INSTAGRAM_POSTS_DOWNLOAD_PATH_ENTRY_X_POSITION = (STANDARD_SIZE[0]/2)-((DOWNLOAD_INSTAGRAM_POSTS_CHANGE_DOWNLOAD_PATH_BUTTON_DIMENSIONS[0]+DOWNLOAD_INSTAGRAM_POSTS_DOWNLOAD_PATH_ENTRY_DIMENSIONS[0]+STANDARD_X_PADDING)/2)
DOWNLOAD_INSTAGRAM_POSTS_DOWNLOAD_PATH_ENTRY_Y_POSITION = DOWNLOAD_INSTAGRAM_POSTS_DOWNLOAD_PATH_LABEL_Y_POSITION + DOWNLOAD_INSTAGRAM_POSTS_DOWNLOAD_PATH_LABEL_DIMENSIONS[1] + STANDARD_Y_PADDING
DOWNLOAD_INSTAGRAM_POSTS_CHANGE_DOWNLOAD_PATH_BUTTON_X_POSITION = DOWNLOAD_INSTAGRAM_POSTS_DOWNLOAD_PATH_ENTRY_X_POSITION + DOWNLOAD_INSTAGRAM_POSTS_DOWNLOAD_PATH_ENTRY_DIMENSIONS[0] + STANDARD_X_PADDING
DOWNLOAD_INSTAGRAM_POSTS_CHANGE_DOWNLOAD_PATH_BUTTON_Y_POSITION = DOWNLOAD_INSTAGRAM_POSTS_DOWNLOAD_PATH_ENTRY_Y_POSITION

## BACK BUTTON
DOWNLOAD_INSTAGRAM_POSTS_BACK_BUTTON_DIMENSIONS = (STANDARD_BUTTON_DIMENSIONS[0], STANDARD_BUTTON_DIMENSIONS[1])
DOWNLOAD_INSTAGRAM_POSTS_BACK_BUTTON_X_POSITION = (STANDARD_SIZE[0]/2)-(DOWNLOAD_INSTAGRAM_POSTS_BACK_BUTTON_DIMENSIONS[0]/2)
DOWNLOAD_INSTAGRAM_POSTS_BACK_BUTTON_Y_POSITION = DOWNLOAD_INSTAGRAM_POSTS_CHANGE_DOWNLOAD_PATH_BUTTON_Y_POSITION + DOWNLOAD_INSTAGRAM_POSTS_CHANGE_DOWNLOAD_PATH_BUTTON_DIMENSIONS[1] + STANDARD_Y_PADDING
##############################################################################################################################################
## DOWNLOAD PROGRESS WINDOW SETTINGS
## LABELS
DOWNLOADING_POST_PROGRESS_WINDOW_LABEL_DIMENSIONS = (STANDARD_LABEL_DIMENSIONS[0]*1.3, STANDARD_LABEL_DIMENSIONS[1])
DOWNLOADING_POST_PROGRESS_WINDOW_LABEL_X_POSITION = (STANDARD_SIZE[0]/2)-(DOWNLOADING_POST_PROGRESS_WINDOW_LABEL_DIMENSIONS[0]/2)
DOWNLOADING_POST_PROGRESS_WINDOW_LABEL_Y_POSITION = STANDARD_Y_PADDING

## PROGRESS BAR
DOWNLOADING_POST_PROGRESS_BAR_DIMENSIONS = (STANDARD_BUTTON_DIMENSIONS[0]*2, STANDARD_BUTTON_DIMENSIONS[1])
DOWNLOADING_POST_PROGRESS_BAR_X_POSITION = (STANDARD_SIZE[0]/2)-(DOWNLOADING_POST_PROGRESS_BAR_DIMENSIONS[0]/2)
DOWNLOADING_POST_PROGRESS_BAR_Y_POSITION = DOWNLOADING_POST_PROGRESS_WINDOW_LABEL_Y_POSITION + DOWNLOADING_POST_PROGRESS_WINDOW_LABEL_DIMENSIONS[1] + STANDARD_Y_PADDING

## LABEL PROGRESS
DOWNLOADING_POST_PROGRESS_LABEL_DIMENSIONS = (STANDARD_LABEL_DIMENSIONS[0], STANDARD_LABEL_DIMENSIONS[1]*STANDARD_LABEL_HEIGHT_REDUCER)
DOWNLOADING_POST_PROGRESS_LABEL_X_POSITION = (STANDARD_SIZE[0]/2)-(DOWNLOADING_POST_PROGRESS_LABEL_DIMENSIONS[0]/2)
DOWNLOADING_POST_PROGRESS_LABEL_Y_POSITION = DOWNLOADING_POST_PROGRESS_BAR_Y_POSITION + DOWNLOADING_POST_PROGRESS_BAR_DIMENSIONS[1] + STANDARD_Y_PADDING


## BACK BUTTON
DOWNLOADING_POST_PROGRESS_BACK_BUTTON_DIMENSIONS = (STANDARD_BUTTON_DIMENSIONS[0], STANDARD_BUTTON_DIMENSIONS[1])
DOWNLOADING_POST_PROGRESS_BACK_BUTTON_X_POSITION = (STANDARD_SIZE[0]/2)-(DOWNLOADING_POST_PROGRESS_BACK_BUTTON_DIMENSIONS[0]/2)
DOWNLOADING_POST_PROGRESS_BACK_BUTTON_Y_POSITION = DOWNLOADING_POST_PROGRESS_LABEL_Y_POSITION + DOWNLOADING_POST_PROGRESS_LABEL_DIMENSIONS[1] + STANDARD_Y_PADDING
##############################################################################################################################################


def center(root, WINDOW_SIZE):
    root.update_idletasks()  # Update "requested size" from geometry manager
    X, Y =  WINDOW_SIZE.split("x")
    x = ((root.winfo_screenwidth() - root.winfo_reqwidth()) / 2) - int(X)/2
    y = ((root.winfo_screenheight() - root.winfo_reqheight()) / 2) - int(Y)/2
    root.geometry("+%d+%d" % (x, y))
    
    root.deiconify()

##############################################################################################################
##############################################################################################################
class MainInterface:
    def __init__(self, master):
        WINDOW_SIZE = f"{STANDARD_SIZE[0]}x{STANDARD_SIZE[1]}"
        self.master = master
        master.title("Main Interface")
        master.geometry(WINDOW_SIZE)
        master.resizable(False, False)
        master.configure(background='#F0F8FF')

        ## OPENING WINDOW AT CENTER
        center(master, WINDOW_SIZE)

        ## STYLES
        self.style = ttk.Style(master)
        self.style.theme_use("xpnative")


        self.label = ttk.Label(master, anchor="center", text="INSTAGRAM AUTOMATION TOOL", justify=tk.RIGHT, background=MAIN_BG_COLOR, font=("Helvetica", 14))
        self.label.place(width=MAIN_WINDOW_LABEL_DIMENSIONS[0], height=MAIN_WINDOW_LABEL_DIMENSIONS[1], x=MAIN_WINDOW_LABEL_X_POSITION, y=MAIN_WINDOW_LABEL_Y_POSITION)

        self.open_tabs_button = ttk.Button(master, text="Open Tabs", command=self.open_tabs)
        self.open_tabs_button.place(width=OPEN_TABS_BUTTON_DIMENSIONS[0], height=OPEN_TABS_BUTTON_DIMENSIONS[1], x=OPEN_TABS_X_POSITION, y=OPEN_TABS_Y_POSITION)

        ## CREATE A BUTTON THAT OPENS A NEW WINDOW CALLED EDIT URLS
        self.edit_urls_button = ttk.Button(master, text="Edit URLs", command=self.edit_urls)
        self.edit_urls_button.place(width=EDIT_URLS_BUTTON_DIMENSIONS[0], height=EDIT_URLS_BUTTON_DIMENSIONS[1], x=EDIT_URLS_X_POSITION, y=EDIT_URLS_Y_POSITION)

        self.open_tabs_button = ttk.Button(master, text="Open Folders", command=self.open_folders)
        self.open_tabs_button.place(width=OPEN_FOLDERS_BUTTON_DIMENSIONS[0], height=OPEN_FOLDERS_BUTTON_DIMENSIONS[1], x=OPEN_FOLDERS_BUTTON_X_POSITION, y=OPEN_FOLDERS_BUTTON_Y_POSITION)


        ## CREATE A BUTTON THAT OPENS A NEW WINDOW CALLED EDIT LOCAL PATHS
        self.edit_local_paths_button = ttk.Button(master, text="Edit Local Paths", command=self.edit_local_paths)
        self.edit_local_paths_button.place(width=EDIT_LOCAL_PATHS_BUTTON_DIMENSIONS[0], height=EDIT_LOCAL_PATHS_BUTTON_DIMENSIONS[1], x=EDIT_LOCAL_PATHS_BUTTON_X_POSITION, y=EDIT_LOCAL_PATHS_BUTTON_Y_POSITION)


        self.open_post_description_file_generator_button = ttk.Button(master, text="Post Description File Generator", command=self.open_post_description_file_generator)
        self.open_post_description_file_generator_button.place(width=POST_DESCRIPTION_FILE_GENERATOR_BUTTON_DIMENSIONS[0], height=POST_DESCRIPTION_FILE_GENERATOR_BUTTON_DIMENSIONS[1], x=POST_DESCRIPTION_FILE_GENERATOR_BUTTON_X_POSITION, y=POST_DESCRIPTION_FILE_GENERATOR_BUTTON_Y_POSITION)

        self.download_instagram_posts = ttk.Button(master, text="Download Instagram Posts", command=self.download_instagram_posts)
        self.download_instagram_posts.place(width=DOWNLOAD_INSTAGRAM_POSTS_EDIT_BUTTON_DIMENSIONS[0], height=DOWNLOAD_INSTAGRAM_POSTS_EDIT_BUTTON_DIMENSIONS[1], x=DOWNLOAD_INSTAGRAM_POSTS_EDIT_BUTTON_X_POSITION, y=DOWNLOAD_INSTAGRAM_POSTS_EDIT_BUTTON_Y_POSITION)
        

    def open_tabs(self):
        brave_path = "C:/Program Files/BraveSoftware/Brave-Browser/Application/brave.exe %s"
        brave = webbrowser.get(brave_path)
        
        ## CREATE AN SQL QUERY THAT SELECTS THE TABLE urls_table AND FETCHES ALL THE URLS
        ## CREATE A FOR LOOP THAT OPENS ALL THE URLS IN THE TABLE urls_table

        conn, cursor = connect_to_sql()
        cursor.execute("SELECT * FROM urls_table")
        urls = cursor.fetchall()
        conn.close()

        
        brave.open("") ## THIS LINE OPENS A NEW BRAVE INSTANCE
        for url in urls:
            brave.open_new(url[1])


    def open_folders(self):
        ## CREATE AN SQL QUERY THAT SELECTS THE TABLE local_paths_table AND FETCHES ALL THE LOCAL PATHS
        ## CREATE A FOR LOOP THAT OPENS ALL THE LOCAL PATH FOLDERS
        conn, cursor = connect_to_sql()
        cursor.execute("SELECT * FROM local_paths_table")
        paths = cursor.fetchall()
        conn.close()

        for current_path in paths:
            path_parsed = os.path.realpath(current_path[1])
            try:
                os.startfile(path_parsed)
            except:
                messagebox.showerror("Error", "The path {} does not exist!".format(path_parsed))


    def edit_urls(self):
        self.master.withdraw()
        self.newWindow = Toplevel(self.master)
        self.app = EditUrls(self.newWindow)

    def edit_local_paths(self):
        self.master.withdraw()
        self.newWindow = Toplevel(self.master)
        self.app = EditLocalPaths(self.newWindow)

    def open_post_description_file_generator(self):
        self.master.withdraw()
        self.newWindow = Toplevel(self.master)
        self.app = PostDescriptionFileGenerator(self.newWindow)

    def download_instagram_posts(self):
        self.master.withdraw()
        self.newWindow = Toplevel(self.master)
        self.app = DownloadInstagramPosts(self.newWindow)


##############################################################################################################
##############################################################################################################
class PostDescriptionFileGenerator:
    def __init__(self, master):
        WINDOW_SIZE = f"{STANDARD_SIZE[0]}x{STANDARD_SIZE[1]}"
        self.master = master
        master.title("Post Description File Generator")
        master.geometry(WINDOW_SIZE)
        master.resizable(False, False)
        master.configure(background='#F0F8FF')

        ## OPENING WINDOW AT CENTER
        center(master, WINDOW_SIZE)

        ## STYLES
        self.style = ttk.Style(master)
        self.style.theme_use("xpnative")

        self.window_label = ttk.Label(master, anchor="center", text="Post Description File Generator", justify=tk.RIGHT, background=MAIN_BG_COLOR, font=("Helvetica", 14))
        self.window_label.place(width=POST_DESCRIPTION_FILE_GENERATOR_WINDOW_LABEL_DIMENSIONS[0], height=POST_DESCRIPTION_FILE_GENERATOR_WINDOW_LABEL_DIMENSIONS[1], x=POST_DESCRIPTION_FILE_GENERATOR_WINDOW_LABEL_X_POSITION, y=POST_DESCRIPTION_FILE_GENERATOR_WINDOW_LABEL_Y_POSITION)

        self.lbl_number_of_posts = ttk.Label(master, anchor="center", text="Number of posts to be created", justify=tk.RIGHT, background=MAIN_BG_COLOR)
        self.lbl_number_of_posts.place(width=POST_DESCRIPTION_NUMBER_OF_POSTS_LABEL_DIMENSIONS[0], height=POST_DESCRIPTION_NUMBER_OF_POSTS_LABEL_DIMENSIONS[1], x=POST_DESCRIPTION_NUMBER_OF_POSTS_LABEL_X_POSITION, y=POST_DESCRIPTION_NUMBER_OF_POSTS_LABEL_Y_POSITION)

        self.entry_number_of_posts = ttk.Entry(master, width=10)
        self.entry_number_of_posts.place(width=NUMBER_OF_POSTS_ENTRY_DIMENSIONS[0], height=NUMBER_OF_POSTS_ENTRY_DIMENSIONS[1], x=NUMBER_OF_POSTS_ENTRY_X_POSITION, y=NUMBER_OF_POSTS_ENTRY_Y_POSITION)

        self.lbl_initial_post_number = ttk.Label(master, anchor="center", text="Initial post number", justify=tk.RIGHT, background=MAIN_BG_COLOR)
        self.lbl_initial_post_number.place(width=POST_DESCRIPTION_INITIAL_POST_NUMBER_LABEL_DIMENSIONS[0], height=POST_DESCRIPTION_INITIAL_POST_NUMBER_LABEL_DIMENSIONS[1], x=POST_DESCRIPTION_INITIAL_POST_NUMBER_LABEL_X_POSITION, y=POST_DESCRIPTION_INITIAL_POST_NUMBER_LABEL_Y_POSITION)

        self.entry_initial_post_number = ttk.Entry(master, width=10)
        self.entry_initial_post_number.place(width=INITIAL_POST_NUMBER_ENTRY_DIMENSIONS[0], height=INITIAL_POST_NUMBER_ENTRY_DIMENSIONS[1], x=INITIAL_POST_NUMBER_ENTRY_X_POSITION, y=INITIAL_POST_NUMBER_ENTRY_Y_POSITION)

        self.button_create_files = ttk.Button(master, text="Create files", command=self.clicked)
        self.button_create_files.place(width=CREATE_FILES_BUTTON_DIMENSIONS[0], height=CREATE_FILES_BUTTON_DIMENSIONS[1], x=CREATE_FILES_BUTTON_X_POSITION, y=CREATE_FILES_BUTTON_Y_POSITION)

        ## CREATE A BUTTON THAT GOES BACK TO THE MAIN INTERFACE
        self.button_back = ttk.Button(master, text="Back", command=self.back)
        self.button_back.place(width=CREATE_FILES_BUTTON_DIMENSIONS[0], height=CREATE_FILES_BUTTON_DIMENSIONS[1], x=CREATE_FILES_BUTTON_X_POSITION, y=CREATE_FILES_BUTTON_Y_POSITION + CREATE_FILES_BUTTON_DIMENSIONS[1] + STANDARD_Y_PADDING)


    def back(self):
        self.master.withdraw()
        self.newWindow = Toplevel(self.master)
        self.app = MainInterface(self.newWindow)

    def create_post_description_text_file(self, path, num_of_posts=1, initial_post_number=1):
        """
        Creates a text file with the description of the post
        :param path: path to the folder where the text file will be created
        :param num_of_posts: number of posts to be created
        :param initial_post_number: number of the first post
        :return: None
        """
        for i in range(num_of_posts):
            with open(path + "\post_{}.txt".format(initial_post_number + i), "a+", encoding='utf-8') as file:
                file.write("Texto da descrição do post {}".format(initial_post_number + i))

        print("Arquivos criados com sucesso")

    def clicked(self):
        try:
            num_of_posts = int(self.lbl_number_of_posts.get())
            initial_post_number = int(self.lbl_initial_post_number.get())
        except ValueError:
            messagebox.showerror("Error", "Please enter a valid number")
            return
        
        path = r"C:\Users\clib_\OneDrive\Desktop\SHAPER\MFCS\DESCRICAO_POSTS\DESCRICAO_POSTS_INSTAGRAM"

        self.create_post_description_text_file(path, num_of_posts, initial_post_number)
        messagebox.showinfo("Success", "Files created successfully!")


##############################################################################################################
##############################################################################################################
class EditUrls:
    def __init__(self, master):
        WINDOW_SIZE = f"{STANDARD_SIZE[0]}x{STANDARD_SIZE[1]}"
        self.master = master
        master.title("Edit URLs")
        master.geometry(WINDOW_SIZE)
        master.resizable(False, False)
        master.configure(background='#F0F8FF')

        ## OPENING WINDOW AT CENTER
        center(master, WINDOW_SIZE)

        ## STYLES
        self.style = ttk.Style(master)
        self.style.theme_use("xpnative")

        self.label = ttk.Label(master, anchor="center", text="Edit URLs", justify=tk.RIGHT, background=MAIN_BG_COLOR, font=("Helvetica", 14))
        self.label.place(width=EDIT_URLS_WINDOW_LABEL_DIMENSIONS[0], height=EDIT_URLS_WINDOW_LABEL_DIMENSIONS[1], x=EDIT_URLS_WINDOW_LABEL_X_POSITION, y=EDIT_URLS_WINDOW_LABEL_Y_POSITION)

        ## CREATE A BUTTON THAT OPENS A NEW WINDOW CALLED INSERT NEW URL
        self.insert_new_url_button = ttk.Button(master, text="Insert New URL", command=self.insert_new_url)
        self.insert_new_url_button.place(width=INSERT_NEW_URL_BUTTON_DIMENSIONS[0], height=INSERT_NEW_URL_BUTTON_DIMENSIONS[1], x=INSERT_NEW_URL_EDIT_BUTTON_X_POSITION, y=INSERT_NEW_URL_EDIT_BUTTON_Y_POSITION)

        self.delete_url_button = ttk.Button(master, text="Delete URLs", command=self.delete_urls)
        self.delete_url_button.place(width=DELETE_URL_EDIT_BUTTON_DIMENSIONS[0], height=DELETE_URL_EDIT_BUTTON_DIMENSIONS[1], x=DELETE_URL_EDIT_BUTTON_X_POSITION, y=DELETE_URL_EDIT_BUTTON_Y_POSITION)

        ## CREATE A BUTTON THAT GOES BACK TO THE MAIN INTERFACE
        self.button_back = ttk.Button(master, text="Back", command=self.back)
        self.button_back.place(width=EDIT_URLS_BACK_BUTTON_DIMENSIONS[0], height=EDIT_URLS_BACK_BUTTON_DIMENSIONS[1], x=EDIT_URLS_BACK_BUTTON_X_POSITION, y=EDIT_URLS_BACK_BUTTON_Y_POSITION)

    
    def insert_new_url(self):
        self.master.withdraw()
        self.newWindow = Toplevel(self.master)
        self.app = InsertNewUrl(self.newWindow)

    def delete_urls(self):
        self.master.withdraw()
        self.newWindow = Toplevel(self.master)
        self.app = DeleteUrls(self.newWindow)

    def back(self):
        self.master.withdraw()
        self.newWindow = Toplevel(self.master)
        self.app = MainInterface(self.newWindow)


##############################################################################################################
##############################################################################################################
class InsertNewUrl:
    def __init__(self, master):
        WINDOW_SIZE = f"{STANDARD_SIZE[0]}x{STANDARD_SIZE[1]}"
        self.master = master
        master.title("Insert New URL")
        master.geometry(WINDOW_SIZE)
        master.resizable(False, False)
        master.configure(background='#F0F8FF')

        ## OPENING WINDOW AT CENTER
        center(master, WINDOW_SIZE)

        ## STYLES
        self.style = ttk.Style(master)
        self.style.theme_use("xpnative")

        self.label = ttk.Label(master, anchor="center", text="Insert New URL", justify=tk.RIGHT, background=MAIN_BG_COLOR, font=("Helvetica", 14))
        self.label.place(width=INSERT_NEW_URL_WINDOW_LABEL_DIMENSIONS[0], height=INSERT_NEW_URL_WINDOW_LABEL_DIMENSIONS[1], x=INSERT_NEW_URL_WINDOW_LABEL_X_POSITION, y=INSERT_NEW_URL_WINDOW_LABEL_Y_POSITION)

        self.label1 = ttk.Label(master, anchor="center", text="URL", justify=tk.RIGHT, background=MAIN_BG_COLOR)
        self.label1.place(width=URL_ENTRY_DIMENSIONS[0], height=URL_ENTRY_DIMENSIONS[1], x=URL_ENTRY_X_POSITION, y=URL_ENTRY_Y_POSITION)

        self.entry1 = ttk.Entry(master, width=10)
        self.entry1.place(width=URL_ENTRY_DIMENSIONS[0], height=URL_ENTRY_DIMENSIONS[1], x=URL_ENTRY_X_POSITION, y=URL_ENTRY_Y_POSITION)

        self.button = ttk.Button(master, text="Insert", command=self.insert)
        self.button.place(width=INSERT_URL_BUTTON_DIMENSIONS[0], height=INSERT_URL_BUTTON_DIMENSIONS[1], x=INSERT_URL_BUTTON_X_POSITION, y=INSERT_URL_BUTTON_Y_POSITION)

        ## CREATE A BUTTON THAT GOES BACK TO THE MAIN INTERFACE
        self.button_back = ttk.Button(master, text="Back", command=self.back)
        self.button_back.place(width=INSERT_NEW_URL_BACK_BUTTON_DIMENSIONS[0], height=INSERT_NEW_URL_BACK_BUTTON_DIMENSIONS[1], x=INSERT_NEW_URL_BACK_BUTTON_X_POSITION, y=INSERT_NEW_URL_BACK_BUTTON_Y_POSITION)
        

    def back(self):
        self.master.withdraw()
        self.newWindow = Toplevel(self.master)
        self.app = EditUrls(self.newWindow)

    def insert(self):
        try:
            url = self.entry1.get()
            if url == "":
                messagebox.showerror("Error", "Please do not leave blank spaces!")
                return
        except ValueError:
            messagebox.showerror("Error", "Please do not leave blank spaces!")
            return

        ## CREATE AN SQL QUERY THAT INSERTS THE URL INTO THE TABLE urls_table

        conn, cursor = connect_to_sql()
        cursor.execute(f"INSERT INTO urls_table (url) VALUES ('{url}')")
        conn.commit()
        delete_duplicates_in_urls_table(conn, cursor)
        conn.commit()
        conn.close()

        messagebox.showinfo("Success", "URL inserted successfully!")


##############################################################################################################
##############################################################################################################
class DeleteUrls:
    def __init__(self, master):
        WINDOW_SIZE = f"{STANDARD_SIZE[0]}x{STANDARD_SIZE[1]}"
        self.master = master
        master.title("Delete URLs")
        master.geometry(WINDOW_SIZE)
        master.resizable(False, False)
        master.configure(background='#F0F8FF')

        ## OPENING WINDOW AT CENTER
        center(master, WINDOW_SIZE)

        ## STYLES
        self.style = ttk.Style(master)
        self.style.theme_use("xpnative")

        self.label = ttk.Label(master, anchor="center", text="Delete URLs", justify=tk.RIGHT, background=MAIN_BG_COLOR, font=("Helvetica", 14))
        self.label.place(width=DELETE_URLS_WINDOW_LABEL_DIMENSIONS[0], height=DELETE_URLS_WINDOW_LABEL_DIMENSIONS[1], x=DELETE_URLS_WINDOW_LABEL_X_POSITION, y=DELETE_URLS_WINDOW_LABEL_Y_POSITION)

        self.option_menu_variable = StringVar(master)
        self.options = self.set_dropdown()

        if self.options:
            self.option_menu = OptionMenu(master, self.option_menu_variable, *self.options)
        else:
            self.option_menu = OptionMenu(master, self.option_menu_variable, "No URLs to delete")
        self.option_menu.place(width=DELETE_URLS_OPTION_MENU_DIMENSIONS[0], height=DELETE_URLS_OPTION_MENU_DIMENSIONS[1], x=DELETE_URL_OPTION_MENU_X_POSITION, y=DELETE_URL_OPTION_MENU_Y_POSITION)

        self.button = ttk.Button(master, text="Delete", command=self.delete)
        self.button.place(width=DELETE_URLS_BUTTON_DIMENSIONS[0], height=DELETE_URLS_BUTTON_DIMENSIONS[1], x=DELETE_URL_BUTTON_X_POSITION, y=DELETE_URL_BUTTON_Y_POSITION)

        ## CREATE A BUTTON THAT GOES BACK TO THE MAIN INTERFACE
        self.button_back = ttk.Button(master, text="Back", command=self.back)
        self.button_back.place(width=DELETE_URLS_BUTTON_DIMENSIONS[0], height=DELETE_URLS_BUTTON_DIMENSIONS[1], x=DELETE_URL_BUTTON_X_POSITION, y=DELETE_URL_BUTTON_Y_POSITION + DELETE_URLS_BUTTON_DIMENSIONS[1] + STANDARD_Y_PADDING)


    def set_dropdown(self):
        ## SETTING THE DROPDOWN TO CHOSE FROM THE URLS IN THE TABLE urls_table
        self.options = fetch_urls_from_urls_table()
        try:
            self.option_menu_variable.set(self.options[0])
            return self.options
        except IndexError:
            messagebox.showerror("Error", "There are no more URLs to delete!")
            self.back()
            return

    def update_option_menu(self):
        menu = self.option_menu["menu"]
        menu.delete(0, "end")
        for string in self.options:
            menu.add_command(label=string, 
                             command=lambda value=string: self.option_menu_variable.set(value))

    def back(self):
        self.master.withdraw()
        self.newWindow = Toplevel(self.master)
        self.app = EditUrls(self.newWindow)

    def delete(self):
        try:
            url = self.option_menu_variable.get()
        except ValueError:
            messagebox.showerror("Error", "Please do not leave blank spaces!")
            return

        ## CREATE AN SQL QUERY THAT DELETES THE URL FROM THE TABLE urls_table

        conn, cursor = connect_to_sql()
        cursor.execute(f"DELETE FROM urls_table WHERE url = '{url}'")
        conn.commit()
        conn.close()

        messagebox.showinfo("Success", "URL deleted successfully!")

        self.options = self.set_dropdown()
        if self.options:
            self.update_option_menu()


##############################################################################################################
##############################################################################################################
class EditLocalPaths:
    def __init__(self, master):
        WINDOW_SIZE = f"{STANDARD_SIZE[0]}x{STANDARD_SIZE[1]}"
        self.master = master
        master.title("Edit Local Paths")
        master.geometry(WINDOW_SIZE)
        master.resizable(False, False)
        master.configure(background='#F0F8FF')

        ## OPENING WINDOW AT CENTER
        center(master, WINDOW_SIZE)

        ## STYLES
        self.style = ttk.Style(master)
        self.style.theme_use("xpnative")

        self.label = ttk.Label(master, anchor="center", text="Edit Local Paths", justify=tk.RIGHT, background=MAIN_BG_COLOR, font=("Helvetica", 14))
        self.label.place(width=EDIT_LOCAL_PATHS_WINDOW_LABEL_DIMENSIONS[0], height=EDIT_LOCAL_PATHS_WINDOW_LABEL_DIMENSIONS[1], x=EDIT_LOCAL_PATHS_WINDOW_LABEL_X_POSITION, y=EDIT_LOCAL_PATHS_WINDOW_LABEL_Y_POSITION)

        self.button = ttk.Button(master, text="Delete Local Paths", command=self.delete_local_paths)
        self.button.place(width=DELETE_LOCAL_PATHS_BUTTON_DIMENSIONS[0], height=DELETE_LOCAL_PATHS_BUTTON_DIMENSIONS[1], x=DELETE_LOCAL_PATH_EDIT_BUTTON_X_POSITION, y=DELETE_LOCAL_PATH_EDIT_BUTTON_Y_POSITION)

        ## CREATE A BUTTON THAT OPENS A NEW WINDOW CALLED INSERT NEW LOCAL PATH
        self.insert_new_local_path_button = ttk.Button(master, text="Insert New Local Path", command=self.insert_new_local_path)
        self.insert_new_local_path_button.place(width=INSERT_NEW_LOCAL_PATH_EDIT_BUTTON_DIMENSIONS[0], height=INSERT_NEW_LOCAL_PATH_EDIT_BUTTON_DIMENSIONS[1], x=INSERT_NEW_LOCAL_PATH_EDIT_BUTTON_X_POSITION, y=INSERT_NEW_LOCAL_PATH_EDIT_BUTTON_Y_POSITION)

        ## CREATE A BUTTON THAT GOES BACK TO THE MAIN INTERFACE
        self.button_back = ttk.Button(master, text="Back", command=self.back)
        self.button_back.place(width=EDIT_LOCAL_PATHS_BACK_BUTTON_DIMENSIONS[0], height=EDIT_LOCAL_PATHS_BACK_BUTTON_DIMENSIONS[1], x=EDIT_LOCAL_PATHS_BACK_BUTTON_X_POSITION, y=EDIT_LOCAL_PATHS_BACK_BUTTON_Y_POSITION)


    def insert_new_local_path(self):
        self.master.withdraw()
        self.newWindow = Toplevel(self.master)
        self.app = InsertNewLocalPath(self.newWindow)

    def delete_local_paths(self):
        self.master.withdraw()
        self.newWindow = Toplevel(self.master)
        self.app = DeleteLocalPaths(self.newWindow)

    def back(self):
        self.master.withdraw()
        self.newWindow = Toplevel(self.master)
        self.app = MainInterface(self.newWindow)


##############################################################################################################
##############################################################################################################
class InsertNewLocalPath:
    def __init__(self, master):
        WINDOW_SIZE = f"{STANDARD_SIZE[0]}x{STANDARD_SIZE[1]}"
        self.master = master
        master.title("Insert New Local Path")
        master.geometry(WINDOW_SIZE)
        master.resizable(False, False)
        master.configure(background='#F0F8FF')

        ## OPENING WINDOW AT CENTER
        center(master, WINDOW_SIZE)

        ## STYLES
        self.style = ttk.Style(master)
        self.style.theme_use("xpnative")

        self.label = ttk.Label(master, anchor="center", text="Insert New Local Path", justify=tk.RIGHT, background=MAIN_BG_COLOR, font=("Helvetica", 14))
        self.label.place(width=INSERT_NEW_LOCAL_PATH_WINDOW_LABEL_DIMENSIONS[0], height=INSERT_NEW_LOCAL_PATH_WINDOW_LABEL_DIMENSIONS[1], x=INSERT_NEW_LOCAL_PATH_WINDOW_LABEL_X_POSITION, y=INSERT_NEW_LOCAL_PATH_WINDOW_LABEL_Y_POSITION)

        self.label1 = ttk.Label(master, anchor="center", text="Local Path", justify=tk.RIGHT, background=MAIN_BG_COLOR)
        self.label1.place(width=LOCAL_PATH_ENTRY_DIMENSIONS[0], height=LOCAL_PATH_ENTRY_DIMENSIONS[1], x=LOCAL_PATH_ENTRY_X_POSITION, y=LOCAL_PATH_ENTRY_Y_POSITION)

        ## INSTEAD OF AN ENTRY, PLEASE ALLOW THE USER TO NAVIGATE ITS OWN PC AND SELECT A FOLDER
        ## THE SELECTED FOLDER WILL BE THE LOCAL PATH

        self.entry1 = ttk.Entry(master, width=10)
        self.entry1.place(width=LOCAL_PATH_ENTRY_DIMENSIONS[0], height=LOCAL_PATH_ENTRY_DIMENSIONS[1], x=LOCAL_PATH_ENTRY_X_POSITION, y=LOCAL_PATH_ENTRY_Y_POSITION)

        self.button = ttk.Button(master, text="Insert", command=self.insert)
        self.button.place(width=INSERT_LOCAL_PATH_BUTTON_DIMENSIONS[0], height=INSERT_LOCAL_PATH_BUTTON_DIMENSIONS[1], x=INSERT_LOCAL_PATH_BUTTON_X_POSITION, y=INSERT_LOCAL_PATH_BUTTON_Y_POSITION)

        self.browse_button = ttk.Button(master, text="Browse", command=self.browse_local_folders)
        self.browse_button.place(width=BROWSE_BUTTON_DIMENSIONS[0], height=BROWSE_BUTTON_DIMENSIONS[1], x=BROWSE_BUTTON_X_POSITION, y=BROWSE_BUTTON_Y_POSITION)

        ## CREATE A BUTTON THAT GOES BACK TO THE MAIN INTERFACE
        self.button_back = ttk.Button(master, text="Back", command=self.back)
        self.button_back.place(width=INSERT_NEW_LOCAL_PATH_BACK_BUTTON_DIMENSIONS[0], height=INSERT_NEW_LOCAL_PATH_BACK_BUTTON_DIMENSIONS[1], x=INSERT_NEW_LOCAL_PATH_BACK_BUTTON_X_POSITION, y=INSERT_NEW_LOCAL_PATH_BACK_BUTTON_Y_POSITION)


    def browse_local_folders(self):
        filename = filedialog.askdirectory()
        self.entry1.insert(END, filename)

    def insert(self):
        try:
            local_path = self.entry1.get()
            if local_path == "":
                messagebox.showerror("Error", "Please do not leave blank spaces!")
                return
        except ValueError:
            messagebox.showerror("Error", "Please do not leave blank spaces!")
            return

        ## CREATE AN SQL QUERY THAT INSERTS THE LOCAL PATH INTO THE TABLE local_paths_table

        conn, cursor = connect_to_sql()
        cursor.execute(f"INSERT INTO local_paths_table (local_path) VALUES ('{local_path}')")
        conn.commit()
        delete_duplicates_in_local_paths_table(conn, cursor)
        conn.commit()
        conn.close()

        messagebox.showinfo("Success", "Local Path inserted successfully!")

    def back(self):
        self.master.withdraw()
        self.newWindow = Toplevel(self.master)
        self.app = EditLocalPaths(self.newWindow)


##############################################################################################################
##############################################################################################################
class DeleteLocalPaths:

    def __init__(self, master):
        WINDOW_SIZE = f"{STANDARD_SIZE[0]}x{STANDARD_SIZE[1]}"
        self.master = master
        master.title("Delete Local Paths")
        master.geometry(WINDOW_SIZE)
        master.resizable(False, False)
        master.configure(background='#F0F8FF')

        ## OPENING WINDOW AT CENTER
        center(master, WINDOW_SIZE)

        ## STYLES
        self.style = ttk.Style(master)
        self.style.theme_use("xpnative")

        self.label = ttk.Label(master, anchor="center", text="Delete Local Paths", justify=tk.RIGHT, background=MAIN_BG_COLOR, font=("Helvetica", 14))
        self.label.place(width=DELETE_LOCAL_PATHS_WINDOW_LABEL_DIMENSIONS[0], height=DELETE_LOCAL_PATHS_WINDOW_LABEL_DIMENSIONS[1], x=DELETE_LOCAL_PATHS_WINDOW_LABEL_X_POSITION, y=DELETE_LOCAL_PATHS_WINDOW_LABEL_Y_POSITION)

        self.option_menu_variable = StringVar(master)
        self.options = self.set_dropdown()

        if self.options:
            self.option_menu = OptionMenu(master, self.option_menu_variable, *self.options)
        else:
            self.option_menu = OptionMenu(master, self.option_menu_variable, "No Local Paths to delete")
        self.option_menu.place(width=DELETE_LOCAL_PATHS_OPTION_MENU_DIMENSIONS[0], height=DELETE_LOCAL_PATHS_OPTION_MENU_DIMENSIONS[1], x=DELETE_LOCAL_PATHS_OPTION_MENU_X_POSITION, y=DELETE_LOCAL_PATHS_OPTION_MENU_Y_POSITION)

        self.button = ttk.Button(master, text="Delete", command=self.delete)
        self.button.place(width=DELETE_LOCAL_PATHS_BUTTON_DIMENSIONS[0], height=DELETE_LOCAL_PATHS_BUTTON_DIMENSIONS[1], x=DELETE_LOCAL_PATHS_BUTTON_X_POSITION, y=DELETE_LOCAL_PATHS_BUTTON_Y_POSITION)

        ## CREATE A BUTTON THAT GOES BACK TO THE MAIN INTERFACE
        self.button_back = ttk.Button(master, text="Back", command=self.back)
        self.button_back.place(width=DELETE_LOCAL_PATHS_BUTTON_DIMENSIONS[0], height=DELETE_LOCAL_PATHS_BUTTON_DIMENSIONS[1], x=DELETE_LOCAL_PATHS_BUTTON_X_POSITION, y=DELETE_LOCAL_PATHS_BUTTON_Y_POSITION + DELETE_LOCAL_PATHS_BUTTON_DIMENSIONS[1] + STANDARD_Y_PADDING)

    def set_dropdown(self):
        ## SETTING THE DROPDOWN TO CHOSE FROM THE URLS IN THE TABLE local_paths_table
        self.options = fetch_local_paths_from_local_paths_table()
        try:
            self.option_menu_variable.set(self.options[0])
            return self.options
        except IndexError:
            messagebox.showerror("Error", "There are no Local Paths to delete!")
            self.back()
            return
        
    def update_option_menu(self):
        menu = self.option_menu["menu"]
        menu.delete(0, "end")
        for string in self.options:
            menu.add_command(label=string, 
                             command=lambda value=string: self.option_menu_variable.set(value))

    def back(self):
        self.master.withdraw()
        self.newWindow = Toplevel(self.master)
        self.app = EditLocalPaths(self.newWindow)

    def delete(self):
        try:
            local_path = self.option_menu_variable.get()
        except ValueError:
            messagebox.showerror("Error", "Please do not leave blank spaces!")
            return

        ## CREATE AN SQL QUERY THAT DELETES THE LOCAL PATH FROM THE TABLE local_paths_table

        conn, cursor = connect_to_sql()
        cursor.execute(f"DELETE FROM local_paths_table WHERE local_path = '{local_path}'")
        conn.commit()
        conn.close()

        messagebox.showinfo("Success", "Local Path deleted successfully!")
        self.options = self.set_dropdown()
        if self.options:
            self.update_option_menu()


##############################################################################################################
##############################################################################################################

##############################################################################################################
class DownloadInstagramPosts:
    def __init__(self, master):
        WINDOW_SIZE = f"{STANDARD_SIZE[0]}x{STANDARD_SIZE[1]}"
        self.master = master
        master.title("Download Instagram Posts")
        master.geometry(WINDOW_SIZE)
        master.resizable(False, False)
        master.configure(background='#F0F8FF')

        ## MAKING SURE DOWNLOAD_PATH_EXISTS
        self.ensure_download_path_exists()

        ## OPENING WINDOW AT CENTER
        center(master, WINDOW_SIZE)
        
        ## STYLES
        self.style = ttk.Style(master)
        self.style.theme_use("xpnative")

        self.lbl_window = ttk.Label(master, anchor="center", text="Instagram Downloader", justify=tk.RIGHT, background=MAIN_BG_COLOR, font=("Helvetica", 14))
        self.lbl_window.place(width=DOWNLOAD_INSTAGRAM_POSTS_WINDOW_LABEL_DIMENSIONS[0], height=DOWNLOAD_INSTAGRAM_POSTS_WINDOW_LABEL_DIMENSIONS[1], x=DOWNLOAD_INSTAGRAM_POSTS_WINDOW_LABEL_X_POSITION, y=DOWNLOAD_INSTAGRAM_POSTS_WINDOW_LABEL_Y_POSITION)

        self.lbl_download_link = ttk.Label(master, anchor="center", text="Instagram Link", justify=tk.RIGHT, background=MAIN_BG_COLOR)
        self.lbl_download_link.place(width=DOWNLOAD_INSTAGRAM_POSTS_LINK_LABEL_DIMENSIONS[0], height=DOWNLOAD_INSTAGRAM_POSTS_LINK_LABEL_DIMENSIONS[1], x=DOWNLOAD_INSTAGRAM_POSTS_LINK_LABEL_X_POSITION, y=DOWNLOAD_INSTAGRAM_POSTS_LINK_LABEL_Y_POSITION)

        self.entry_download_link = ttk.Entry(master, width=10)
        self.entry_download_link.place(width=DOWNLOAD_INSTAGRAM_POSTS_LINK_ENTRY_DIMENSIONS[0], height=DOWNLOAD_INSTAGRAM_POSTS_LINK_ENTRY_DIMENSIONS[1], x=DOWNLOAD_INSTAGRAM_POSTS_LINK_ENTRY_X_POSITION, y=DOWNLOAD_INSTAGRAM_POSTS_LINK_ENTRY_Y_POSITION)

        ## CREATE A BUTTON THAT DOWNLOADS THE POST
        self.button_download = ttk.Button(master, text="Download", command=self.download)
        self.button_download.place(width=DOWNLOAD_INSTAGRAM_POSTS_DOWNLOAD_BUTTON_DIMENSIONS[0], height=DOWNLOAD_INSTAGRAM_POSTS_DOWNLOAD_BUTTON_DIMENSIONS[1], x=DOWNLOAD_INSTAGRAM_POSTS_DOWNLOAD_BUTTON_X_POSITION, y=DOWNLOAD_INSTAGRAM_POSTS_DOWNLOAD_BUTTON_Y_POSITION)

        ## FILE NAME ENTRY
        self.entry_file_name = ttk.Entry(master, width=10)
        self.entry_file_name.place(width=DOWNLOAD_INSTAGRAM_POSTS_FILE_NAME_ENTRY_DIMENSIONS[0], height=DOWNLOAD_INSTAGRAM_POSTS_FILE_NAME_ENTRY_DIMENSIONS[1], x=DOWNLOAD_INSTAGRAM_POSTS_FILE_NAME_ENTRY_X_POSITION, y=DOWNLOAD_INSTAGRAM_POSTS_FILE_NAME_ENTRY_Y_POSITION)

        ## FILE NAME LABEL
        self.label_file_name = ttk.Label(master, anchor="center", text="File Name", justify=tk.RIGHT, background=MAIN_BG_COLOR)
        self.label_file_name.place(width=DOWNLOAD_INSTAGRAM_POSTS_FILE_NAME_LABEL_DIMENSIONS[0], height=DOWNLOAD_INSTAGRAM_POSTS_FILE_NAME_LABEL_DIMENSIONS[1], x=DOWNLOAD_INSTAGRAM_POSTS_FILE_NAME_LABEL_X_POSITION, y=DOWNLOAD_INSTAGRAM_POSTS_FILE_NAME_LABEL_Y_POSITION)

        ## SHOWING THE USER THE CURRENT DOWNLOAD PATH
        self.label_show_download_path = ttk.Label(master, anchor="center", text="Download Path", justify=tk.RIGHT, background=MAIN_BG_COLOR)
        self.label_show_download_path.place(width=DOWNLOAD_INSTAGRAM_POSTS_DOWNLOAD_PATH_LABEL_DIMENSIONS[0], height=DOWNLOAD_INSTAGRAM_POSTS_DOWNLOAD_PATH_LABEL_DIMENSIONS[1], x=DOWNLOAD_INSTAGRAM_POSTS_DOWNLOAD_PATH_LABEL_X_POSITION, y=DOWNLOAD_INSTAGRAM_POSTS_DOWNLOAD_PATH_LABEL_Y_POSITION)

        self.entry_current_download_path = ttk.Entry(master, width=10)
        self.entry_current_download_path.place(width=DOWNLOAD_INSTAGRAM_POSTS_DOWNLOAD_PATH_ENTRY_DIMENSIONS[0], height=DOWNLOAD_INSTAGRAM_POSTS_DOWNLOAD_PATH_ENTRY_DIMENSIONS[1], x=DOWNLOAD_INSTAGRAM_POSTS_DOWNLOAD_PATH_ENTRY_X_POSITION, y=DOWNLOAD_INSTAGRAM_POSTS_DOWNLOAD_PATH_ENTRY_Y_POSITION)
        self.path = self.fetch_current_download_path()
        self.entry_current_download_path.insert(END, self.path)

        ## CREATE A BUTTON SO THE USER CAN CHANGE THE DOWNLOAD_PATH
        self.button_change_download_path = ttk.Button(master, text="Change Download Path", command=self.change_download_path)
        self.button_change_download_path.place(width=DOWNLOAD_INSTAGRAM_POSTS_CHANGE_DOWNLOAD_PATH_BUTTON_DIMENSIONS[0], height=DOWNLOAD_INSTAGRAM_POSTS_CHANGE_DOWNLOAD_PATH_BUTTON_DIMENSIONS[1], x=DOWNLOAD_INSTAGRAM_POSTS_CHANGE_DOWNLOAD_PATH_BUTTON_X_POSITION, y=DOWNLOAD_INSTAGRAM_POSTS_CHANGE_DOWNLOAD_PATH_BUTTON_Y_POSITION)

        ## CREATE A BUTTON THAT GOES BACK TO THE MAIN INTERFACE
        self.button_back = ttk.Button(master, text="Back", command=self.back)
        self.button_back.place(width=DOWNLOAD_INSTAGRAM_POSTS_BACK_BUTTON_DIMENSIONS[0], height=DOWNLOAD_INSTAGRAM_POSTS_BACK_BUTTON_DIMENSIONS[1], x=DOWNLOAD_INSTAGRAM_POSTS_BACK_BUTTON_X_POSITION, y=DOWNLOAD_INSTAGRAM_POSTS_BACK_BUTTON_Y_POSITION)

    def back(self):
        self.master.withdraw()
        self.newWindow = Toplevel(self.master)
        self.app = MainInterface(self.newWindow)

    def ensure_download_path_exists(self):
        ## CHECK IF THE DOWNLOAD PATH FILE EXISTS
        if not os.path.exists(DOWNLOAD_REPOSITORY_CONFIG):
            os.makedirs(DOWNLOAD_REPOSITORY_CONFIG)
            ## CREATE A JSON FILE WITH THE PATH TO THE DOWNLOAD REPOSITORY
            download_repository = {"download_repository": DOWNLOAD_REPOSITORY_CONFIG}
            with open(DOWNLOAD_REPOSITORY_CONFIG+DOWNLOAD_CONFIG_FILE_NAME, "w") as file:
                json.dump(download_repository, file)
                
    def fetch_current_download_path(self):
        ## READ JSON CONFIG FILE
        with open(DOWNLOAD_REPOSITORY_CONFIG+DOWNLOAD_CONFIG_FILE_NAME, "r") as file:
            data = json.load(file)
        return data["download_repository"]

    def change_download_path(self):
        ## CHANGE THE JSON CONFIG FILE WITH THE NEW DOWNLOAD PATH
        new_download_path = filedialog.askdirectory()
        download_repository = {"download_repository": new_download_path}
        with open(DOWNLOAD_REPOSITORY_CONFIG+DOWNLOAD_CONFIG_FILE_NAME, "w") as file:
            json.dump(download_repository, file)
        ## TELL THE USER DOWNLOAD PATH HAS BEEN CHANGED
        if new_download_path == "":
            messagebox.showerror("Error", "You havent select any path, no changes were made!")
            return
        else:
            messagebox.showinfo("Success", f"Download Path changed successfully to:\n{new_download_path}")
            self.entry_current_download_path.insert(END, new_download_path)
            self.set_current_path()

    def set_current_path(self):
        ## SETTING THE DROPDOWN TO CHOSE FROM THE URLS IN THE TABLE local_paths_table
        self.path = self.fetch_current_download_path()
        self.entry_current_download_path.insert(END, self.path)

    def download(self):
        try:
            url = self.entry_download_link.get()
            if url == "":
                messagebox.showerror("Error", "Please do not leave blank spaces!")
                return
        except ValueError:
            messagebox.showerror("Error", "Please do not leave blank spaces!")
            return
        
        try:
            filename = self.entry_file_name.get()
            if filename == "":
                messagebox.showerror("Error", "Please do not leave filename blank!")
                return
        except ValueError:
            messagebox.showerror("Error", "Please do not leave filename blank!")
            return
        
        ## DOWNLOAD THE POST
        ## FETCH THE CURRENT DOWNLOAD LINK
        download_link = self.entry_download_link.get()

        ## DOWNLOAD THE POST
        self.open_download_progress(download_link, self.path, filename)

        
    ## CREATE A NEW WINDOW
    def open_download_progress(self, download_link, path, filename):
        self.newWindow = Toplevel(self.master)
        self.app = DownloadingPostProgress(self.newWindow, download_link, path, filename)


class DownloadingPostProgress:
    def __init__(self, master, download_link, download_path, filename):
        WINDOW_SIZE = f"{STANDARD_SIZE[0]}x{STANDARD_SIZE[1]}"
        self.master = master
        self.download_link = download_link
        self.download_path = download_path
        self.filename = filename
        master.title("Downloading Post")
        master.geometry(WINDOW_SIZE)
        master.resizable(False, False)
        master.configure(background='#F0F8FF')

        ## OPENING WINDOW AT CENTER
        center(master, WINDOW_SIZE)
        
        ## STYLES
        self.style = ttk.Style(master)
        self.style.theme_use("xpnative")

        self.lbl_window = ttk.Label(master, anchor="center", text="Downloading Post", justify=tk.RIGHT, background=MAIN_BG_COLOR, font=("Helvetica", 14))
        self.lbl_window.place(width=DOWNLOADING_POST_PROGRESS_WINDOW_LABEL_DIMENSIONS[0], height=DOWNLOADING_POST_PROGRESS_WINDOW_LABEL_DIMENSIONS[1], x=DOWNLOADING_POST_PROGRESS_WINDOW_LABEL_X_POSITION, y=DOWNLOADING_POST_PROGRESS_WINDOW_LABEL_Y_POSITION)

        self.progress_bar = ttk.Progressbar(master, orient=HORIZONTAL, length=DOWNLOADING_POST_PROGRESS_BAR_DIMENSIONS[0], mode='determinate', value=0, maximum=100)
        self.progress_bar.place(width=DOWNLOADING_POST_PROGRESS_BAR_DIMENSIONS[0], height=DOWNLOADING_POST_PROGRESS_BAR_DIMENSIONS[1], x=DOWNLOADING_POST_PROGRESS_BAR_X_POSITION, y=DOWNLOADING_POST_PROGRESS_BAR_Y_POSITION)

        self.lbl_progress = ttk.Label(master, anchor="center", text="0%", justify=tk.RIGHT, background=MAIN_BG_COLOR)
        self.lbl_progress.place(width=DOWNLOADING_POST_PROGRESS_LABEL_DIMENSIONS[0], height=DOWNLOADING_POST_PROGRESS_LABEL_DIMENSIONS[1], x=DOWNLOADING_POST_PROGRESS_LABEL_X_POSITION, y=DOWNLOADING_POST_PROGRESS_LABEL_Y_POSITION)

        self.button_back = ttk.Button(master, text="Back", command=self.back)
        self.button_back.place(width=DOWNLOADING_POST_PROGRESS_BACK_BUTTON_DIMENSIONS[0], height=DOWNLOADING_POST_PROGRESS_BACK_BUTTON_DIMENSIONS[1], x=DOWNLOADING_POST_PROGRESS_BACK_BUTTON_X_POSITION, y=DOWNLOADING_POST_PROGRESS_BACK_BUTTON_Y_POSITION)
        
        for i in range(1000):
            if i == 999:
                downloaded = self.download()
                self.update_progress_bar(downloaded)

        


    def back(self):
        self.master.withdraw()

    ## IF PROGRESS BAR REACHES 100, SHOW USER DOWNLOAD WAS SUCCESSFUL
    def update_progress_bar(self, downloaded):
        if downloaded:
            for i in range(101):
                self.progress_bar['value'] = i
                self.lbl_progress['text'] = f"{i}%"
                self.master.update_idletasks()

            if self.progress_bar['value'] == 100:
                messagebox.showinfo("Success", "Download was successful!")
                self.master.withdraw()
        else:
            messagebox.showerror("Error", "Download was not successful!")
            self.master.withdraw()

        


    def download(self):
        ## DOWNLOAD THE POST USING instaloader
        insta = Instaloader()
        post_id = self.download_link.split("/")[-2]
        print(f"self.download_link {self.download_link}")
        print(f"post_id {post_id}")
        print(f"dowload_path {self.download_path}")
        post = Post.from_shortcode(insta.context, post_id)
        standard_media_dump_post_path = f"{DOWNLOAD_REPOSITORY}\\post_{post_id}"
        is_downloaded = insta.download_post(post, target=standard_media_dump_post_path)
        if is_downloaded:
            ## MOVE FILE DESCRITPION TO THE DOWNLOAD PATH
            for file in os.listdir(standard_media_dump_post_path):
                if file.endswith(".mp4"):
                    shutil.move(os.path.join(standard_media_dump_post_path, file), self.download_path+f"\\{file}")
                    os.rename(self.download_path+f"\\{file}", self.download_path+f"\\{self.filename}.mp4")
                elif file.endswith(".txt"):
                    shutil.move(os.path.join(standard_media_dump_post_path, file), self.download_path+f"\\{file}")
                    os.rename(self.download_path+f"\\{file}", self.download_path+f"\\{self.filename}.txt")
                else:
                    ## REMOVE FILE
                    os.remove(os.path.join(standard_media_dump_post_path, file))
            ## REMOVE EMPTY FOLDER
            os.rmdir(standard_media_dump_post_path)
            return True
        else:
            return False
        

        



##############################################################################################################
##############################################################################################################
if __name__ == "__main__":
    ## CREATE THE DATABASE AND TABLES IF THEY DONT EXIST
    create_database()
    create_tables()
    root = ThemedTk() ## TKINTER WITH A LOT OF DIFFERENT THEMES
    root.withdraw()
    
    my_gui = MainInterface(root)
    root.mainloop()