@REM ## CREATE A COMMAND LINE THAT EXECUTES THE PYTHON FILE main_interface.py
@REM ## THE COMMAND LINE SHOULD BE ABLE TO EXECUTE THE FILE EVEN IF THE USER IS NOT IN THE SAME DIRECTORY AS THE FILL


@REM ## RUN THE COMMAND LINE

@REM ## START OF SCRIPT
@REM ## SET THE CURRENT DIRECTORY TO THE DIRECTORY OF THE SCRIPT
cd %~dp0

@REM ## SET THE PYTHON FILE TO BE EXECUTED
set python_file=main_interface.py

@REM ## SET THE PYTHON EXECUTABLE
set python_executable=python

@REM ## SET THE COMMAND LINE
set command_line=%python_executable% %python_file%

@REM EXECUTE THE COMMAND LINE
%command_line%

@REM ## END OF SCRIPT
